//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Calls')
export class CallsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  CallID: number;

  @Column('text', { nullable: true })
  CallerNumber: string;

  @Column('text', { nullable: true })
  ReceiverNumber: string;

  @Column('date', { nullable: true })
  StartTime: Date;

  @Column('date', { nullable: true })
  EndTime: Date;

  @Column('text', { nullable: true })
  Status: string;
}
