//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Calls: {
      name: 'Calls',
      fields: {
        CallID: 'Call Id',
        CallerNumber: 'Caller Number',
        ReceiverNumber: 'Receiver Number',
        StartTime: 'Start Time',
        EndTime: 'End Time',
        Status: 'Status',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Calls: {
      name: 'Calls (fr)',
      fields: {
        CallID: 'Call Id (fr)',
        CallerNumber: 'Caller Number (fr)',
        ReceiverNumber: 'Receiver Number (fr)',
        StartTime: 'Start Time (fr)',
        EndTime: 'End Time (fr)',
        Status: 'Status (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
